---
# - name: Print return information from the previous task
  # ansible.builtin.debug:
    # var: "{{ hostvars.get(item).ansible_host }}"
    # verbosity: 2
- name: metal_provision_wait_ssh
  ansible.builtin.wait_for_connection:
    # host: "{{ hostvars.get(item).ansible_host }}"
    # port: 22
    # delay: 20
    # search_regex: OpenSSH
    # timeout: 5
    connect_timeout: 20
    sleep: 10
    delay: 2
    timeout: 60
  connection: local
  loop: "{{ query('inventory_hostnames', 'tag_mfd') }}"
