---
- name: metal_meta_print_project_id
  become: true
  become_method: sudo
  ansible.builtin.debug:
    ### msg: "{{ lookup('env', 'METAL_PROJ_ID') }}"
    msg: "{{ ansible_env }}"
  delegate_to: localhost

- name: metal_meta_print_project_id
  #become: true
  #become_method: sudo
  ansible.builtin.debug:
    ### msg: "{{ lookup('env', 'METAL_PROJ_ID') }}"
    msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
  delegate_to: localhost

- name: metal_meta_print_project_id
  #become: true
  #become_method: sudo
  ansible.builtin.debug:
    ### msg: "{{ lookup('env', 'METAL_PROJ_ID') }}"
    msg: "'{{ lookup('ansible.builtin.env', 'METAL_PROJ_ID') }}'"
  delegate_to: localhost

- name: mdfs_sys_mangle_2_10
  ansible.builtin.shell:
    cmd: "echo $METAL_PROJ_ID"
