---
- name: provision_mfd
  hosts: localhost
  gather_facts: false
  strategy: free
  # vars:
    # - ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: metal_provision_instance
      include_role:
        name: metal
        tasks_from: play_metal_get_or_provision_instances.yaml

    - meta: refresh_inventory

    - name: metal_instance_wait
      include_role:
        name: metal
        tasks_from: play_metal_instance_wait.yaml
